---
  - hosts: web
    connection: ssh
    become: True
    become_user: root  
    roles:
      - role: geerlingguy.nginx
        nginx_worker_processes: >-
          "{{ ansible_processor_vcpus | default(ansible_processor_count) }}"
        nginx_worker_rlimit_nofile: "8192"
        nginx_events_use: "epoll"
        nginx_worker_connections: "1024"
        nginx_multi_accept: "off"

        nginx_log_format: |-
          '$remote_addr - $remote_user [$time_local] "$request" '
          '$status $body_bytes_sent "$http_referer" '
          '"$http_user_agent" "$http_x_forwarded_for"'

        nginx_error_log: "/var/log/nginx/error.log warn"
        nginx_access_log: "/var/log/nginx/access.log main buffer=16k flush=2m"

        nginx_server_tokens: "off"

        nginx_sendfile: "on"
        nginx_tcp_nopush: "on"
        nginx_tcp_nodelay: "on"

        nginx_keepalive_timeout: "65"
        nginx_keepalive_requests: "100"

        nginx_client_body_timeout: "10"
        nginx_client_header_timeout: "10"
        nginx_send_timeout: "10"

        nginx_client_max_body_size: "64m"
        nginx_server_names_hash_bucket_size: "64"

# This setting should be true if you're proxing websocket
        nginx_websocket: false

        nginx_ssl_ciphers: EECDH+AESGCM:EDH+AESGCM:AES256+EECDH:AES256+EDH:HIGH
        nginx_ssl_certificate_path: ""
        nginx_ssl_certificate_key_path: ""
        nginx_ssl_dhparam_path: ""
        nginx_ssl_stapling_verify: "on"

# Global Proxy settings
        nginx_proxy_cache_path: ""
        nginx_proxy_request_buffering: "on"
        nginx_proxy_read_timeout: 60
        nginx_proxy_connect_timeout: 60